
version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket 492b
                                   --output-template-file Helloworld.yml
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
artifacts:
  type: jar
  files:
    - Helloworld.yml
    - Helloworld.jar
  discard-paths: yes
