
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello world
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloworldFunctionHandler.handleRequest
      Runtime: java8
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /helloworld
            Method: GET

