
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello world
Resources:
  Helloworld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: helloworld.HelloworldFunctionHandler
      Runtime: java8
      CodeUri: HelloWorld-1.0.jar
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /helloworld
            Method: GET

